//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerMaintenanceSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerMaintenanceSystem.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid address..
        /// </summary>
        internal static string CustomerAddressTextBoxValidationErrorMessage {
            get {
                return ResourceManager.GetString("CustomerAddressTextBoxValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid car number..
        /// </summary>
        internal static string CustomerCarNoTextBoxValidationErrorMessage {
            get {
                return ResourceManager.GetString("CustomerCarNoTextBoxValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid make..
        /// </summary>
        internal static string CustomerMakeTextBoxValidationErrorMessage {
            get {
                return ResourceManager.GetString("CustomerMakeTextBoxValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid name..
        /// </summary>
        internal static string CustomerNameTextBoxValidationErrorMessage {
            get {
                return ResourceManager.GetString("CustomerNameTextBoxValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer table is updated..
        /// </summary>
        internal static string CustomerTableIsUpdatedMessage {
            get {
                return ResourceManager.GetString("CustomerTableIsUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid car number..
        /// </summary>
        internal static string JobDetailsCarNoTextBoxValidationErrorMessage {
            get {
                return ResourceManager.GetString("JobDetailsCarNoTextBoxValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job date should not be in the future..
        /// </summary>
        internal static string JobDetailsJobDateDateTimePickerValidationErrorMessage {
            get {
                return ResourceManager.GetString("JobDetailsJobDateDateTimePickerValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (There are no records in the customer table.).
        /// </summary>
        internal static string ThereAreNoRecordsInTheCustomerTableMessage {
            get {
                return ResourceManager.GetString("ThereAreNoRecordsInTheCustomerTableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Worker table is updated..
        /// </summary>
        internal static string WorkerTableIsUpdatedMessage {
            get {
                return ResourceManager.GetString("WorkerTableIsUpdatedMessage", resourceCulture);
            }
        }
    }
}
